using System.Collections.Generic;
using System.Linq;

namespace JobAggregator.BusinessLogic.Services.Scrapers
{
    public static class LocationIdLookup
    {
        public static readonly Dictionary<string, int> ProvinceNameToId = new(System.StringComparer.OrdinalIgnoreCase)
        {
            { "Hà Nội", 73 },
            { "TP.HCM", 122 },
            { "An Giang", 129 },
            { "Bà Rịa - Vũng Tàu", 121 },
            { "Bắc Giang", 87 },
            { "Bắc Kạn", 76 },
            { "Bạc Liêu", 134 },
            { "Bắc Ninh", 90 },
            { "Bến Tre", 125 },
            { "Bình Dương", 119 },
            { "Bình Phước", 117 },
            { "Bình Thuận", 111 },
            { "Bình Định", 107 },
            { "Cà Mau", 135 },
            { "Cần Thơ", 131 },
            { "Cao Bằng", 75 },
            { "Gia Lai", 113 },
            { "Hà Giang", 74 },
            { "Hà Nam", 95 },
            { "Hà Tĩnh", 100 },
            { "Hải Dương", 91 },
            { "Hải Phòng", 92 },
            { "Hậu Giang", 132 },
            { "Hòa Bình", 83 },
            { "Hưng Yên", 93 },
            { "Khánh Hòa", 109 },
            { "Kiên Giang", 130 },
            { "Kon Tum", 112 },
            { "Lai Châu", 80 },
            { "Lâm Đồng", 116 },
            { "Lạng Sơn", 85 },
            { "Lào Cai", 78 },
            { "Long An", 123 },
            { "Nam Định", 96 },
            { "Nghệ An", 99 },
            { "Ninh Bình", 97 },
            { "Ninh Thuận", 110 },
            { "Nước ngoài", 140 },
            { "Phú Thọ", 88 },
            { "Phú Yên", 108 },
            { "Quảng Bình", 101 },
            { "Quảng Nam", 105 },
            { "Quảng Ngãi", 106 },
            { "Quảng Ninh", 86 },
            { "Quảng Trị", 102 },
            { "Sóc Trăng", 133 },
            { "Sơn La", 81 },
            { "Tây Ninh", 118 },
            { "Thái Bình", 94 },
            { "Thái Nguyên", 84 },
            { "Thanh Hóa", 98 },
            { "Thừa Thiên Huế", 103 },
            { "Tiền Giang", 124 },
            { "Toàn quốc", 136 },
            { "Trà Vinh", 126 },
            { "Tuyên Quang", 77 },
            { "Vĩnh Long", 127 },
            { "Vĩnh Phúc", 89 },
            { "Yên Bái", 82 },
            { "Đà Nẵng", 104 },
            { "Đắk Lắk", 114 },
            { "Đắk Nông", 115 },
            { "Điện Biên", 79 },
            { "Đồng Nai", 120 },
            { "Đồng Tháp", 128 },
        };

        public static readonly ILookup<string, string> DistrictNameToUrlPath = new (string Name, string Path)[]
        {
            ("Quận 1", "viec-lam-quan-1-tp-hcm-d308.html"),
            ("Quận 3", "viec-lam-quan-3-tp-hcm-d318.html"),
            ("Quận 4", "viec-lam-quan-4-tp-hcm-d321.html"),
            ("Quận 5", "viec-lam-quan-5-tp-hcm-d322.html"),
            ("Quận 6", "viec-lam-quan-6-tp-hcm-d323.html"),
            ("Quận 7", "viec-lam-quan-7-tp-hcm-d326.html"),
            ("Quận 8", "viec-lam-quan-8-tp-hcm-d324.html"),
            ("Quận 10", "viec-lam-quan-10-tp-hcm-d319.html"),
            ("Quận 11", "viec-lam-quan-11-tp-hcm-d320.html"),
            ("Quận 12", "viec-lam-quan-12-tp-hcm-d309.html"),
            ("A Lưới", "viec-lam-huyen-a-luoi-thua-thien-hue-d651.html"),
            ("An Biên", "viec-lam-huyen-an-bien-kien-giang-d370.html"),
            ("An Dương", "viec-lam-huyen-an-duong-hai-phong-d294.html"),
            ("An Khê", "viec-lam-thi-xa-an-khe-gia-lai-d199.html"),
            ("An Lão", "viec-lam-huyen-an-lao-hai-phong-d295.html"),
            ("An Lão", "viec-lam-huyen-an-lao-binh-dinh-d62.html"),
            ("An Minh", "viec-lam-huyen-an-minh-kien-giang-d371.html"),
            ("An Nhơn", "viec-lam-thi-xa-an-nhon-binh-dinh-d69.html"),
            ("An Phú", "viec-lam-huyen-an-phu-an-giang-d3.html"),
            ("Ân Thi", "viec-lam-huyen-an-thi-hung-yen-d348.html"),
            ("Anh Sơn", "viec-lam-huyen-anh-son-nghe-an-d461.html"),
            ("Ayun Pa", "viec-lam-thi-xa-ayun-pa-gia-lai-d200.html"),
            ("Ba Bể", "viec-lam-huyen-ba-be-bac-kan-d32.html"),
            ("Ba Chẽ", "viec-lam-huyen-ba-che-quang-ninh-d553.html"),
            ("Ba Đình", "viec-lam-quan-ba-dinh-ha-noi-d232.html"),
            ("Ba Đồn", "viec-lam-huyen-ba-don-quang-binh-d100000003.html"),
            ("Bà Rịa", "viec-lam-thanh-pho-ba-ria-ba-ria-vung-tau-d13.html"),
            ("Bá Thước", "viec-lam-huyen-ba-thuoc-thanh-hoa-d623.html"),
            ("Ba Tơ", "viec-lam-huyen-ba-to-quang-ngai-d543.html"),
            ("Ba Tri", "viec-lam-huyen-ba-tri-ben-tre-d59.html"),
            ("Ba Vì", "viec-lam-huyen-ba-vi-ha-noi-d250.html"),
            ("Bác Ái", "viec-lam-huyen-bac-ai-ninh-thuan-d478.html"),
            ("Bắc Bình", "viec-lam-huyen-bac-binh-binh-thuan-d92.html"),
            ("Bắc Giang", "viec-lam-thanh-pho-bac-giang-bac-giang-d20.html"),
            ("Bắc Hà", "viec-lam-huyen-bac-ha-lao-cai-d420.html"),
            ("Bắc Kạn", "viec-lam-thi-xa-bac-kan-bac-kan-d30.html"),
            ("Bạc Liêu", "viec-lam-thanh-pho-bac-lieu-bac-lieu-d38.html"),
            ("Bắc Mê", "viec-lam-huyen-bac-me-ha-giang-d221.html"),
            ("Bắc Ninh", "viec-lam-thanh-pho-bac-ninh-bac-ninh-d45.html"),
            ("Bắc Quang", "viec-lam-huyen-bac-quang-ha-giang-d224.html"),
            ("Bắc Sơn", "viec-lam-huyen-bac-son-lang-son-d411.html"),
            ("Bắc Tân Uyên", "viec-lam-huyen-bac-tan-uyen-binh-duong-d100000002.html"),
            ("Bắc Trà My", "viec-lam-huyen-bac-tra-my-quang-nam-d526.html"),
            ("Bắc Từ Liêm", "viec-lam-quan-bac-tu-liem-ha-noi-d246.html"),
            ("Bắc Yên", "viec-lam-huyen-bac-yen-son-la-d585.html"),
            ("Bạch Long Vĩ", "viec-lam-huyen-bach-long-vi-hai-phong-d300.html"),
            ("Bạch Thông", "viec-lam-huyen-bach-thong-bac-kan-d34.html"),
            ("Bảo Lạc", "viec-lam-huyen-bao-lac-cao-bang-d119.html"),
            ("Bảo Lâm", "viec-lam-huyen-bao-lam-cao-bang-d118.html"),
            ("Bảo Lâm", "viec-lam-huyen-bao-lam-lam-dong-d401.html"),
            ("Bảo Lộc", "viec-lam-thanh-pho-bao-loc-lam-dong-d394.html"),
            ("Bảo Thắng", "viec-lam-huyen-bao-thang-lao-cai-d421.html"),
            ("Bảo Yên", "viec-lam-huyen-bao-yen-lao-cai-d422.html"),
            ("Bát Xát", "viec-lam-huyen-bat-xat-lao-cai-d417.html"),
            ("Bàu Bàng", "viec-lam-huyen-bau-bang-binh-duong-d100000000.html"),
            ("Bến Cát", "viec-lam-huyen-ben-cat-binh-duong-d74.html"),
            ("Bến Cầu", "viec-lam-huyen-ben-cau-tay-ninh-d599.html"),
            ("Bến Lức", "viec-lam-huyen-ben-luc-long-an-d433.html"),
            ("Bến Tre", "viec-lam-thanh-pho-ben-tre-ben-tre-d53.html"),
            ("Biên Hòa", "viec-lam-thanh-pho-bien-hoa-dong-nai-d175.html"),
            ("Bỉm Sơn", "viec-lam-thi-xa-bim-son-thanh-hoa-d619.html"),
            ("Bình Chánh", "viec-lam-huyen-binh-chanh-tp-hcm-d329.html"),
            ("Bình Đại", "viec-lam-huyen-binh-dai-ben-tre-d58.html"),
            ("Bình Gia", "viec-lam-huyen-binh-gia-lang-son-d407.html"),
            ("Bình Giang", "viec-lam-huyen-binh-giang-hai-duong-d281.html"),
            ("Bình Liêu", "viec-lam-huyen-binh-lieu-quang-ninh-d549.html"),
            ("Bình Long", "viec-lam-thi-xa-binh-long-binh-phuoc-d81.html"),
            ("Bình Lục", "viec-lam-huyen-binh-luc-ha-nam-d230.html"),
            ("Bình Minh", "viec-lam-huyen-binh-minh-vinh-long-d684.html"),
            ("Bình Sơn", "viec-lam-huyen-binh-son-quang-ngai-d532.html"),
            ("Bình Tân", "viec-lam-quan-binh-tan-tp-hcm-d325.html"),
            ("Bình Tân", "viec-lam-huyen-binh-tan-vinh-long-d686.html"),
            ("Bình Thạnh", "viec-lam-quan-binh-thanh-tp-hcm-d313.html"),
            ("Bình Thủy", "viec-lam-quan-binh-thuy-can-tho-d110.html"),
            ("Bình Xuyên", "viec-lam-huyen-binh-xuyen-vinh-phuc-d692.html"),
            ("Bố Trạch", "viec-lam-huyen-bo-trach-quang-binh-d510.html"),
            ("Bù Đăng", "viec-lam-huyen-bu-dang-binh-phuoc-d87.html"),
            ("Bù Đốp", "viec-lam-huyen-bu-dop-binh-phuoc-d84.html"),
            ("Bù Gia Mập", "viec-lam-huyen-bu-gia-map-binh-phuoc-d82.html"),
            ("Buôn Ðôn", "viec-lam-huyen-buon-don-dak-lak-d142.html"),
            ("Buôn Hồ", "viec-lam-thi-xa-buon-ho-dak-lak-d139.html"),
            ("Buôn Ma Thuột", "viec-lam-thanh-pho-buon-ma-thuot-dak-lak-d138.html"),
            ("Cà Mau", "viec-lam-thanh-pho-ca-mau-ca-mau-d99.html"),
            ("Cái Bè", "viec-lam-huyen-cai-be-tien-giang-d657.html"),
            ("Cai Lậy", "viec-lam-huyen-cai-lay-tien-giang-d658.html"),
            ("Cái Nước", "viec-lam-huyen-cai-nuoc-ca-mau-d103.html"),
            ("Cái Răng", "viec-lam-quan-cai-rang-can-tho-d111.html"),
            ("Cẩm Giàng", "viec-lam-huyen-cam-giang-hai-duong-d280.html"),
            ("Cẩm Khê", "viec-lam-huyen-cam-khe-phu-tho-d491.html"),
            ("Cam Lâm", "viec-lam-huyen-cam-lam-khanh-hoa-d355.html"),
            ("Cẩm Lệ", "viec-lam-quan-cam-le-da-nang-d135.html"),
            ("Cam Lộ", "viec-lam-huyen-cam-lo-quang-tri-d566.html"),
            ("Cẩm Mỹ", "viec-lam-huyen-cam-my-dong-nai-d182.html"),
            ("Cẩm Phả", "viec-lam-thanh-pho-cam-pha-quang-ninh-d547.html"),
            ("Cam Ranh", "viec-lam-thanh-pho-cam-ranh-khanh-hoa-d354.html"),
            ("Cẩm Thủy", "viec-lam-huyen-cam-thuy-thanh-hoa-d627.html"),
            ("Cẩm Xuyên", "viec-lam-huyen-cam-xuyen-ha-tinh-d271.html"),
            ("Cần Đước", "viec-lam-huyen-can-duoc-long-an-d436.html"),
            ("Cần Giờ", "viec-lam-huyen-can-gio-tp-hcm-d331.html"),
            ("Cần Giuộc", "viec-lam-huyen-can-giuoc-long-an-d437.html"),
            ("Can Lộc", "viec-lam-huyen-can-loc-ha-tinh-d268.html"),
            ("Càng Long", "viec-lam-huyen-cang-long-tra-vinh-d665.html"),
            ("Cao Bằng", "viec-lam-thi-xa-cao-bang-cao-bang-d117.html"),
            ("Cao Lãnh", "viec-lam-thanh-pho-cao-lanh-thanh-pho-dong-thap-d186.html"),
            ("Cao Lãnh", "viec-lam-huyen-cao-lanh-huyen-dong-thap-d193.html"),
            ("Cao Lộc", "viec-lam-huyen-cao-loc-lang-son-d409.html"),
            ("Cao Phong", "viec-lam-huyen-cao-phong-hoa-binh-d337.html"),
            ("Cát Hải", "viec-lam-huyen-cat-hai-hai-phong-d299.html"),
            ("Cát Tiên", "viec-lam-huyen-cat-tien-lam-dong-d404.html"),
            ("Cầu Giấy", "viec-lam-quan-cau-giay-ha-noi-d236.html"),
            ("Cầu Kè", "viec-lam-huyen-cau-ke-tra-vinh-d666.html"),
            ("Cầu Ngang", "viec-lam-huyen-cau-ngang-tra-vinh-d669.html"),
            ("Châu Đốc", "viec-lam-thi-xa-chau-doc-an-giang-d2.html"),
            ("Châu Đức", "viec-lam-huyen-chau-duc-ba-ria-vung-tau-d14.html"),
            ("Châu Phú", "viec-lam-huyen-chau-phu-an-giang-d6.html"),
            ("Châu Thành", "viec-lam-huyen-chau-thanh-an-giang-d9.html"),
            ("Châu Thành", "viec-lam-huyen-chau-thanh-hau-giang-d304.html"),
            ("Châu Thành", "viec-lam-huyen-chau-thanh-ben-tre-d54.html"),
            ("Châu Thành", "viec-lam-huyen-chau-thanh-soc-trang-d571.html"),
            ("Châu Thành", "viec-lam-huyen-chau-thanh-tay-ninh-d596.html"),
            ("Châu Thành", "viec-lam-huyen-chau-thanh-kien-giang-d367.html"),
            ("Châu Thành", "viec-lam-huyen-chau-thanh-tien-giang-d659.html"),
            ("Châu Thành", "viec-lam-huyen-chau-thanh-tra-vinh-d668.html"),
            ("Châu Thành", "viec-lam-huyen-chau-thanh-long-an-d438.html"),
            ("Châu Thành", "viec-lam-huyen-chau-thanh-dong-thap-d197.html"),
            ("Châu Thành A", "viec-lam-huyen-chau-thanh-a-hau-giang-d303.html"),
            ("Chi Lăng", "viec-lam-huyen-chi-lang-lang-son-d413.html"),
            ("Chí Linh", "viec-lam-thi-xa-chi-linh-hai-duong-d275.html"),
            ("Chiêm Hóa", "viec-lam-huyen-chiem-hoa-tuyen-quang-d674.html"),
            ("Chợ Đồn", "viec-lam-huyen-cho-don-bac-kan-d35.html"),
            ("Chợ Gạo", "viec-lam-huyen-cho-gao-tien-giang-d660.html"),
            ("Chợ Lách", "viec-lam-huyen-cho-lach-ben-tre-d55.html"),
            ("Chợ Mới", "viec-lam-huyen-cho-moi-an-giang-d10.html"),
            ("Chợ Mới", "viec-lam-huyen-cho-moi-bac-kan-d36.html"),
            ("Chơn Thành", "viec-lam-huyen-chon-thanh-binh-phuoc-d88.html"),
            ("Chư Păh", "viec-lam-huyen-chu-pah-gia-lai-d203.html"),
            ("Chư Prông", "viec-lam-huyen-chu-prong-gia-lai-d208.html"),
            ("Chư Pưh", "viec-lam-huyen-chu-puh-gia-lai-d214.html"),
            ("Chư Sê", "viec-lam-huyen-chu-se-gia-lai-d209.html"),
            ("Chương Mỹ", "viec-lam-huyen-chuong-my-ha-noi-d256.html"),
            ("Cờ Đỏ", "viec-lam-huyen-co-do-can-tho-d114.html"),
            ("Cô Tô", "viec-lam-huyen-co-to-quang-ninh-d558.html"),
            ("Cồn Cỏ", "viec-lam-huyen-con-co-quang-tri-d569.html"),
            ("Con Cuông", "viec-lam-huyen-con-cuong-nghe-an-d459.html"),
            ("Côn Đảo", "viec-lam-huyen-con-dao-ba-ria-vung-tau-d19.html"),
            ("Củ Chi", "viec-lam-huyen-cu-chi-tp-hcm-d327.html"),
            ("Cư Jút", "viec-lam-huyen-cu-jut-dak-lak-d156.html"),
            ("Cư Jút", "viec-lam-huyen-cu-jut-dak-nong-d159.html"),
            ("Cư Kuin", "viec-lam-huyen-cu-kuin-dak-lak-d152.html"),
            ("Cù Lao Dung", "viec-lam-huyen-cu-lao-dung-soc-trang-d574.html"),
            ("Cư M'gar", "viec-lam-huyen-cu-m-gar-dak-lak-d143.html"),
            ("Cửa Lò", "viec-lam-thi-xa-cua-lo-nghe-an-d450.html"),
            ("Dak Rlấp", "viec-lam-huyen-dak-r-lap-dak-nong-d163.html"),
            ("Dầu Tiếng", "viec-lam-huyen-dau-tieng-binh-duong-d73.html"),
            ("Dĩ An", "viec-lam-thi-xa-di-an-binh-duong-d77.html"),
            ("Di Linh", "viec-lam-huyen-di-linh-lam-dong-d400.html"),
            ("Diễn Châu", "viec-lam-huyen-dien-chau-nghe-an-d462.html"),
            ("Diên Khánh", "viec-lam-huyen-dien-khanh-khanh-hoa-d359.html"),
            ("Dương Kinh", "viec-lam-quan-kinh-duong-hai-phong-d292.html"),
            ("Dương Minh Châu", "viec-lam-huyen-duong-minh-chau-tay-ninh-d595.html"),
            ("Duy Tiên", "viec-lam-huyen-duy-tien-ha-nam-d227.html"),
            ("Duy Xuyên", "viec-lam-huyen-duy-xuyen-quang-nam-d519.html"),
            ("Duyên Hải", "viec-lam-huyen-duyen-hai-tra-vinh-d671.html"),
            ("Đà Bắc", "viec-lam-huyen-da-bac-hoa-binh-d333.html"),
            ("Đạ Huoai", "viec-lam-huyen-da-huoai-lam-dong-d402.html"),
            ("Đà Lạt", "viec-lam-thanh-pho-da-lat-lam-dong-d393.html"),
            ("Đạ Tẻh", "viec-lam-huyen-da-teh-lam-dong-d403.html"),
            ("Đại Lộc", "viec-lam-huyen-dai-loc-quang-nam-d517.html"),
            ("Đại Từ", "viec-lam-huyen-dai-tu-thai-nguyen-d615.html"),
            ("Đak Đoa", "viec-lam-huyen-dak-doa-gia-lai-d202.html"),
            ("Đak Glêi", "viec-lam-huyen-dak-glei-kon-tum-d378.html"),
            ("Đắk Glong", "viec-lam-huyen-dak-glong-dak-nong-d158.html"),
            ("Đak Hà", "viec-lam-huyen-dak-ha-kon-tum-d383.html"),
            ("Đak Mil", "viec-lam-huyen-dak-mil-dak-lak-d155.html"),
            ("Đắk Mil", "viec-lam-huyen-dak-mil-dak-nong-d160.html"),
            ("Đak Nông", "viec-lam-huyen-dak-nong-dak-lak-d154.html"),
            ("Đak Pơ", "viec-lam-huyen-dak-po-gia-lai-d210.html"),
            ("Đắk R'lấp", "viec-lam-huyen-dak-rlap-dak-lak-d165.html"),
            ("Đắk Song", "viec-lam-huyen-dak-song-dak-nong-d162.html"),
            ("Đak Tô", "viec-lam-huyen-dak-to-kon-tum-d380.html"),
            ("Đakrông", "viec-lam-huyen-dakrong-quang-tri-d565.html"),
            ("Đầm Dơi", "viec-lam-huyen-dam-doi-ca-mau-d104.html"),
            ("Đầm Hà", "viec-lam-huyen-dam-ha-quang-ninh-d551.html"),
            ("Đam Rông", "viec-lam-huyen-dam-rong-lam-dong-d395.html"),
            ("Đan Phượng", "viec-lam-huyen-dan-phuong-ha-noi-d252.html"),
            ("Đất Đỏ", "viec-lam-huyen-dat-do-ba-ria-vung-tau-d17.html"),
            ("Điện Bàn", "viec-lam-huyen-dien-ban-quang-nam-d518.html"),
            ("Điện Biên", "viec-lam-huyen-dien-bien-dien-bien-d171.html"),
            ("Điện Biên Đông", "viec-lam-huyen-dien-bien-dong-dien-bien-d172.html"),
            ("Định Hóa", "viec-lam-huyen-dinh-hoa-thai-nguyen-d611.html"),
            ("Đình Lập", "viec-lam-huyen-dinh-lap-lang-son-d415.html"),
            ("Định Quán", "viec-lam-huyen-dinh-quan-dong-nai-d179.html"),
            ("Đô Lương", "viec-lam-huyen-do-luong-nghe-an-d464.html"),
            ("Đồ Sơn", "viec-lam-quan-do-son-hai-phong-d291.html"),
            ("Đoan Hùng", "viec-lam-huyen-doan-hung-phu-tho-d486.html"),
            ("Đơn Dương", "viec-lam-huyen-don-duong-lam-dong-d398.html"),
            ("Đông Anh", "viec-lam-huyen-dong-anh-ha-noi-d244.html"),
            ("Đống Đa", "viec-lam-quan-dong-da-ha-noi-d237.html"),
            ("Đông Giang", "viec-lam-huyen-dong-giang-quang-nam-d516.html"),
            ("Đông Hà", "viec-lam-thanh-pho-dong-ha-quang-tri-d560.html"),
            ("Đông Hải", "viec-lam-huyen-dong-hai-bac-lieu-d43.html"),
            ("Đông Hòa", "viec-lam-huyen-dong-hoa-phu-yen-d505.html"),
            ("Đồng Hới", "viec-lam-thanh-pho-dong-hoi-quang-binh-d506.html"),
            ("Đông Hưng", "viec-lam-huyen-dong-hung-thai-binh-d604.html"),
            ("Đồng Hỷ", "viec-lam-huyen-dong-hy-thai-nguyen-d613.html"),
            ("Đồng Phú", "viec-lam-huyen-dong-phu-binh-phuoc-d86.html"),
            ("Đông Sơn", "viec-lam-huyen-dong-son-thanh-hoa-d642.html"),
            ("Đông Triều", "viec-lam-huyen-dong-trieu-quang-ninh-d556.html"),
            ("Đồng Văn", "viec-lam-huyen-dong-van-ha-giang-d216.html"),
            ("Đồng Xoài", "viec-lam-thi-xa-dong-xoai-binh-phuoc-d79.html"),
            ("Đồng Xuân", "viec-lam-huyen-dong-xuan-phu-yen-d499.html"),
            ("Đức Cơ", "viec-lam-huyen-duc-co-gia-lai-d207.html"),
            ("Đức Hòa", "viec-lam-huyen-duc-hoa-long-an-d432.html"),
            ("Đức Huệ", "viec-lam-huyen-duc-hue-long-an-d431.html"),
            ("Đức Linh", "viec-lam-huyen-duc-linh-binh-thuan-d96.html"),
            ("Đức Phổ", "viec-lam-huyen-duc-pho-quang-ngai-d542.html"),
            ("Đức Thọ", "viec-lam-huyen-duc-tho-ha-tinh-d265.html"),
            ("Đức Trọng", "viec-lam-huyen-duc-trong-lam-dong-d399.html"),
            ("Ea H'leo", "viec-lam-huyen-ea-h-leo-dak-lak-d140.html"),
            ("Ea Kar", "viec-lam-huyen-ea-kar-dak-lak-d146.html"),
            ("Ea Súp", "viec-lam-huyen-ea-sup-dak-lak-d141.html"),
            ("Gia Bình", "viec-lam-huyen-gia-binh-bac-ninh-d51.html"),
            ("Gia Lâm", "viec-lam-huyen-gia-lam-ha-noi-d245.html"),
            ("Gia Lộc", "viec-lam-huyen-gia-loc-hai-duong-d282.html"),
            ("Gia Nghĩa", "viec-lam-thi-xa-gia-nghia-dak-nong-d157.html"),
            ("Giá Rai", "viec-lam-huyen-gia-rai-bac-lieu-d42.html"),
            ("Gia Viễn", "viec-lam-huyen-gia-vien-ninh-binh-d472.html"),
            ("Giang Thành", "viec-lam-huyen-giang-thanh-kien-giang-d376.html"),
            ("Giao Thủy", "viec-lam-huyen-giao-thuy-nam-dinh-d447.html"),
            ("Gio Linh", "viec-lam-huyen-gio-linh-quang-tri-d564.html"),
            ("Giồng Riềng", "viec-lam-huyen-giong-gieng-kien-giang-d368.html"),
            ("Giồng Trôm", "viec-lam-huyen-giong-trom-ben-tre-d57.html"),
            ("Gò Công", "viec-lam-thi-xa-go-cong-tien-giang-d655.html"),
            ("Gò Công Đông", "viec-lam-huyen-go-cong-dong-tien-giang-d662.html"),
            ("Gò Công Tây", "viec-lam-huyen-go-cong-tay-tien-giang-d661.html"),
            ("Gò Dầu", "viec-lam-huyen-go-dau-tay-ninh-d598.html"),
            ("Gò Quao", "viec-lam-huyen-go-quao-kien-giang-d369.html"),
            ("Gò Vấp", "viec-lam-quan-go-vap-tp-hcm-d312.html"),
            ("Hà Đông", "viec-lam-quan-ha-dong-ha-noi-d241.html"),
            ("Hà Giang", "viec-lam-thi-xa-ha-giang-ha-giang-d215.html"),
            ("Hạ Hòa", "viec-lam-huyen-ha-hoa-phu-tho-d487.html"),
            ("Hạ Lang", "viec-lam-huyen-ha-lang-cao-bang-d124.html"),
            ("Hạ Long", "viec-lam-thanh-pho-ha-long-quang-ninh-d545.html"),
            ("Hà Quảng", "viec-lam-huyen-ha-quang-cao-bang-d121.html"),
            ("Hà Tiên", "viec-lam-thi-xa-ha-tien-kien-giang-d363.html"),
            ("Hà Tĩnh", "viec-lam-thanh-pho-ha-tinh-ha-tinh-d262.html"),
            ("Hà Trung", "viec-lam-huyen-ha-trung-thanh-hoa-d629.html"),
            ("Hải An", "viec-lam-quan-hai-an-hai-phong-d289.html"),
            ("Hai Bà Trưng", "viec-lam-quan-hai-ba-trung-ha-noi-d238.html"),
            ("Hải Châu", "viec-lam-quan-hai-chau-da-nang-d132.html"),
            ("Hải Dương", "viec-lam-thanh-pho-hai-duong-hai-duong-d274.html"),
            ("Hải Hà", "viec-lam-huyen-hai-ha-quang-ninh-d552.html"),
            ("Hải Hậu", "viec-lam-huyen-hai-hau-nam-dinh-d448.html"),
            ("Hải Lăng", "viec-lam-huyen-hai-lang-quang-tri-d568.html"),
            ("Hàm Tân", "viec-lam-huyen-ham-tan-binh-thuan-d97.html"),
            ("Hàm Thuận Bắc", "viec-lam-huyen-ham-thuan-bac-binh-thuan-d93.html"),
            ("Hàm Thuận Nam", "viec-lam-huyen-ham-thuan-nam-binh-thuan-d94.html"),
            ("Hàm Yên", "viec-lam-huyen-ham-yen-tuyen-quang-d675.html"),
            ("Hậu Lộc", "viec-lam-huyen-hau-loc-thanh-hoa-d637.html"),
            ("Hiệp Đức", "viec-lam-huyen-hiep-duc-quang-nam-d523.html"),
            ("Hiệp Hòa", "viec-lam-huyen-hiep-hoa-bac-giang-d29.html"),
            ("Hòa An", "viec-lam-huyen-hoa-an-cao-bang-d127.html"),
            ("Hòa Bình", "viec-lam-huyen-hoa-binh-bac-lieu-d44.html"),
            ("Hòa Bình", "viec-lam-thanh-pho-hoa-binh-hoa-binh-d332.html"),
            ("Hoa Lư", "viec-lam-huyen-hoa-lu-ninh-binh-d473.html"),
            ("Hòa Thành", "viec-lam-huyen-hoa-thanh-tay-ninh-d597.html"),
            ("Hòa Vang", "viec-lam-huyen-hoa-vang-da-nang-d136.html"),
            ("Hoài Ân", "viec-lam-huyen-hoai-an-binh-dinh-d64.html"),
            ("Hoài Đức", "viec-lam-huyen-hoai-duc-ha-noi-d253.html"),
            ("Hoài Nhơn", "viec-lam-huyen-hoai-nhon-binh-dinh-d63.html"),
            ("Hoàn Kiếm", "viec-lam-quan-hoan-kiem-ha-noi-d233.html"),
            ("Hoằng Hóa", "viec-lam-huyen-hoang-hoa-thanh-hoa-d636.html"),
            ("Hoàng Mai", "viec-lam-quan-hoang-mai-ha-noi-d239.html"),
            ("Hoàng Sa", "viec-lam-huyen-hoang-sa-da-nang-d137.html"),
            ("Hoàng Su Phì", "viec-lam-huyen-hoang-su-phi-ha-giang-d222.html"),
            ("Hoành Bồ", "viec-lam-huyen-hoanh-bo-quang-ninh-d555.html"),
            ("Hóc Môn", "viec-lam-huyen-hoc-mon-tp-hcm-d328.html"),
            ("Hội An", "viec-lam-thanh-pho-hoi-an-quang-nam-d514.html"),
            ("Hòn Đất", "viec-lam-huyen-hon-dat-kien-giang-d365.html"),
            ("Hớn Quản", "viec-lam-huyen-hon-quan-binh-phuoc-d85.html"),
            ("Hồng Bàng", "viec-lam-quan-hong-bang-hai-phong-d286.html"),
            ("Hồng Dân", "viec-lam-huyen-hong-dan-bac-lieu-d39.html"),
            ("Hồng Lĩnh", "viec-lam-thi-xa-hong-linh-ha-tinh-d263.html"),
            ("Hồng Ngự", "viec-lam-thi-xa-hong-ngu-thi-xa-dong-thap-d188.html"),
            ("Hồng Ngự", "viec-lam-thi-xa-hong-ngu-huyen-dong-thap-d190.html"),
            ("Huế", "viec-lam-thanh-pho-hue-thua-thien-hue-d645.html"),
            ("Hưng Hà", "viec-lam-huyen-hung-ha-thai-binh-d603.html"),
            ("Hưng Nguyên", "viec-lam-huyen-hung-nguyen-nghe-an-d468.html"),
            ("Hưng Yên", "viec-lam-thanh-pho-hung-yen-hung-yen-d343.html"),
            ("Hướng Hóa", "viec-lam-huyen-huong-hoa-quang-tri-d563.html"),
            ("Hương Khê", "viec-lam-huyen-huong-khe-ha-tinh-d269.html"),
            ("Hương Sơn", "viec-lam-huyen-huong-son-ha-tinh-d264.html"),
            ("Hương Thủy", "viec-lam-thi-xa-huong-thuy-thua-thien-hue-d649.html"),
            ("Hương Trà", "viec-lam-thi-xa-huong-tra-thua-thien-hue-d650.html"),
            ("Hữu Lũng", "viec-lam-huyen-huu-lung-lang-son-d412.html"),
            ("Ia Grai", "viec-lam-huyen-ia-grai-gia-lai-d204.html"),
            ("Ia Pa", "viec-lam-huyen-ia-pa-gia-lai-d211.html"),
            ("Kbang", "viec-lam-huyen-kbang-gia-lai-d201.html"),
            ("Kế Sách", "viec-lam-huyen-ke-sach-soc-trang-d572.html"),
            ("Khánh Sơn", "viec-lam-huyen-khanh-son-khanh-hoa-d360.html"),
            ("Khánh Vĩnh", "viec-lam-huyen-khanh-vinh-khanh-hoa-d358.html"),
            ("Khoái Châu", "viec-lam-huyen-khoai-chau-hung-yen-d349.html"),
            ("Kiến An", "viec-lam-quan-kien-an-hai-phong-d290.html"),
            ("Kiên Hải", "viec-lam-huyen-kien-hai-kien-giang-d374.html"),
            ("Kiên Lương", "viec-lam-huyen-kien-luong-kien-giang-d364.html"),
            ("Kiến Thụy", "viec-lam-huyen-kien-thuy-hai-phong-d296.html"),
            ("Kiến Xương", "viec-lam-huyen-kien-xuong-thai-binh-d607.html"),
            ("Kim Bảng", "viec-lam-huyen-kim-bang-ha-nam-d228.html"),
            ("Kim Bôi", "viec-lam-huyen-kim-boi-hoa-binh-d336.html"),
            ("Kim Động", "viec-lam-huyen-kim-dong-hung-yen-d350.html"),
            ("Kim Sơn", "viec-lam-huyen-kim-son-ninh-binh-d475.html"),
            ("Kim Thành", "viec-lam-huyen-kim-thanh-hai-duong-d278.html"),
            ("Kinh Môn", "viec-lam-huyen-kinh-mon-hai-duong-d277.html"),
            ("Kon Plông", "viec-lam-huyen-kon-plong-kon-tum-d381.html"),
            ("Kon Rẫy", "viec-lam-huyen-kon-ray-kon-tum-d382.html"),
            ("Kon Tum", "viec-lam-thanh-pho-kon-tum-kon-tum-d377.html"),
            ("Kông Chro", "viec-lam-huyen-kong-chro-gia-lai-d206.html"),
            ("Krông Ana", "viec-lam-huyen-krong-a-na-dak-lak-d150.html"),
            ("Krông Bông", "viec-lam-huyen-krong-bong-dak-lak-d148.html"),
            ("Krông Buk", "viec-lam-huyen-krong-buk-dak-lak-d144.html"),
            ("Krông Năng", "viec-lam-huyen-krong-nang-dak-lak-d145.html"),
            ("Krông Nô", "viec-lam-huyen-krong-no-dak-lak-d153.html"),
            ("Krông Nô", "viec-lam-huyen-krong-no-dak-nong-d161.html"),
            ("Krông Pa", "viec-lam-huyen-krong-pa-gia-lai-d212.html"),
            ("Krông Pắc", "viec-lam-huyen-krong-pac-dak-lak-d149.html"),
            ("Kỳ Anh", "viec-lam-huyen-ky-anh-ha-tinh-d272.html"),
            ("Kỳ Sơn", "viec-lam-huyen-ky-son-hoa-binh-d334.html"),
            ("Kỳ Sơn", "viec-lam-huyen-ky-son-nghe-an-d454.html"),
            ("La Gi", "viec-lam-thi-xa-la-gi-binh-thuan-d90.html"),
            ("Lạc Dương", "viec-lam-huyen-lac-duong-lam-dong-d396.html"),
            ("Lạc Sơn", "viec-lam-huyen-lac-son-hoa-binh-d340.html"),
            ("Lạc Thủy", "viec-lam-huyen-lac-thuy-hoa-binh-d342.html"),
            ("Lai Châu", "viec-lam-thi-xa-lai-chau-lai-chau-d386.html"),
            ("Lai Vung", "viec-lam-huyen-lai-vung-dong-thap-d196.html"),
            ("Lak", "viec-lam-huyen-lak-dak-lak-d151.html"),
            ("Lâm Bình", "viec-lam-huyen-lam-binh-tuyen-quang-d678.html"),
            ("Lâm Hà", "viec-lam-huyen-lam-ha-lam-dong-d397.html"),
            ("Lâm Thao", "viec-lam-huyen-lam-thao-phu-tho-d493.html"),
            ("Lang Chánh", "viec-lam-huyen-lang-chanh-thanh-hoa-d625.html"),
            ("Lạng Giang", "viec-lam-huyen-lang-giang-bac-giang-d23.html"),
            ("Lạng Sơn", "viec-lam-thanh-pho-lang-son-lang-son-d405.html"),
            ("Lào Cai", "viec-lam-thanh-pho-lao-cai-lao-cai-d416.html"),
            ("Lập Thạch", "viec-lam-huyen-lap-thach-vinh-phuc-d689.html"),
            ("Lấp Vò", "viec-lam-huyen-lap-vo-dong-thap-d195.html"),
            ("Lê Chân", "viec-lam-quan-le-chan-hai-phong-d288.html"),
            ("Lệ Thủy", "viec-lam-huyen-le-thuy-quang-binh-d512.html"),
            ("Liên Chiểu", "viec-lam-quan-lien-chieu-da-nang-d130.html"),
            ("Lộc Bình", "viec-lam-huyen-loc-binh-lang-son-d414.html"),
            ("Lộc Hà", "viec-lam-huyen-loc-ha-ha-tinh-d273.html"),
            ("Lộc Ninh", "viec-lam-huyen-loc-ninh-binh-phuoc-d83.html"),
            ("Long Biên", "viec-lam-quan-long-bien-ha-noi-d235.html"),
            ("Long Điền", "viec-lam-huyen-long-dien-ba-ria-vung-tau-d16.html"),
            ("Long Hồ", "viec-lam-huyen-long-ho-vinh-long-d680.html"),
            ("Long Khánh", "viec-lam-thi-xa-long-khanh-dong-nai-d176.html"),
            ("Long Mỹ", "viec-lam-huyen-long-my-hau-giang-d307.html"),
            ("Long Phú", "viec-lam-huyen-long-phu-soc-trang-d575.html"),
            ("Long Thành", "viec-lam-huyen-long-thanh-dong-nai-d183.html"),
            ("Long Xuyên", "viec-lam-thanh-pho-long-xuyen-an-giang-d1.html"),
            ("Lục Nam", "viec-lam-huyen-luc-nam-bac-giang-d24.html"),
            ("Lục Ngạn", "viec-lam-huyen-luc-ngan-bac-giang-d25.html"),
            ("Lục Yên", "viec-lam-huyen-luc-yen-yen-bai-d699.html"),
            ("Lương Sơn", "viec-lam-huyen-luong-son-hoa-binh-d335.html"),
            ("Lương Tài", "viec-lam-huyen-luong-tai-bac-ninh-d52.html"),
            ("Lý Nhân", "viec-lam-huyen-ly-nhan-ha-nam-d231.html"),
            ("Lý Sơn", "viec-lam-huyen-ly-son-quang-ngai-d544.html"),
            ("M'Drăk", "viec-lam-huyen-m-drak-dak-lak-d147.html"),
            ("Mai Châu", "viec-lam-huyen-mai-chau-hoa-binh-d339.html"),
            ("Mai Sơn", "viec-lam-huyen-mai-son-son-la-d589.html"),
            ("Mang Thít", "viec-lam-huyen-mang-thit-vinh-long-d681.html"),
            ("Mang Yang", "viec-lam-huyen-mang-yang-gia-lai-d205.html"),
            ("Mê Linh", "viec-lam-huyen-me-linh-vinh-phuc-d696.html"),
            ("Mê Linh", "viec-lam-huyen-me-linh-ha-noi-d249.html"),
            ("Mèo Vạc", "viec-lam-huyen-meo-vac-ha-giang-d217.html"),
            ("Minh Hóa", "viec-lam-huyen-minh-hoa-quang-binh-d507.html"),
            ("Minh Long", "viec-lam-huyen-minh-long-quang-ngai-d539.html"),
            ("Mỏ Cày", "viec-lam-huyen-mo-cay-ben-tre-d56.html"),
            ("Mộ Đức", "viec-lam-huyen-mo-duc-quang-ngai-d541.html"),
            ("Mộc Châu", "viec-lam-huyen-moc-chau-son-la-d587.html"),
            ("Mộc Hóa", "viec-lam-huyen-moc-hoa-long-an-d428.html"),
            ("Móng Cái", "viec-lam-thanh-pho-mong-cai-quang-ninh-d546.html"),
            ("Mù Cang Chải", "viec-lam-huyen-mu-cang-chai-yen-bai-d701.html"),
            ("Mường Ảng", "viec-lam-huyen-muong-ang-dien-bien-d173.html"),
            ("Mường Chà", "viec-lam-huyen-muong-cha-dien-bien-d168.html"),
            ("Mường Khương", "viec-lam-huyen-muong-khuong-lao-cai-d418.html"),
            ("Mường La", "viec-lam-huyen-muong-la-son-la-d584.html"),
            ("Mường Lát", "viec-lam-huyen-muong-lat-thanh-hoa-d621.html"),
            ("Mường Lay", "viec-lam-thi-xa-muong-lay-dien-bien-d166.html"),
            ("Mường Nhé", "viec-lam-huyen-muong-nhe-dien-bien-d167.html"),
            ("Mường Tè", "viec-lam-huyen-muong-te-lai-chau-d388.html"),
            ("Mỹ Đức", "viec-lam-huyen-my-duc-ha-noi-d261.html"),
            ("Mỹ Hào", "viec-lam-huyen-my-hao-hung-yen-d347.html"),
            ("Mỹ Lộc", "viec-lam-huyen-my-loc-nam-dinh-d440.html"),
            ("Mỹ Tho", "viec-lam-thanh-pho-my-tho-tien-giang-d654.html"),
            ("Mỹ Tú", "viec-lam-huyen-my-tu-soc-trang-d573.html"),
            ("Mỹ Xuyên", "viec-lam-huyen-my-xuyen-soc-trang-d576.html"),
            ("Nà Hang", "viec-lam-huyen-na-hang-tuyen-quang-d673.html"),
            ("Na Rì", "viec-lam-huyen-na-ri-bac-kan-d37.html"),
            ("Năm Căn", "viec-lam-huyen-nam-can-ca-mau-d105.html"),
            ("Nam Đàn", "viec-lam-huyen-nam-dan-nghe-an-d467.html"),
            ("Nam Định", "viec-lam-thanh-pho-nam-dinh-nam-dinh-d439.html"),
            ("Nam Đông", "viec-lam-huyen-nam-dong-thua-thien-hue-d653.html"),
            ("Nam Giang", "viec-lam-huyen-nam-giang-quang-nam-d521.html"),
            ("Nậm Pồ", "viec-lam-huyen-nam-po-dien-bien-d174.html"),
            ("Nam Sách", "viec-lam-huyen-nam-sach-hai-duong-d276.html"),
            ("Nam Trà My", "viec-lam-huyen-nam-tra-my-quang-nam-d527.html"),
            ("Nam Trực", "viec-lam-huyen-nam-truc-nam-dinh-d444.html"),
            ("Nam Từ Liêm", "viec-lam-quan-nam-tu-liem-ha-noi-d247.html"),
            ("Ngã Bảy", "viec-lam-thi-xa-nga-bay-hau-giang-d302.html"),
            ("Ngã Năm", "viec-lam-huyen-nga-nam-soc-trang-d577.html"),
            ("Nga Sơn", "viec-lam-huyen-nga-son-thanh-hoa-d638.html"),
            ("Ngân Sơn", "viec-lam-huyen-ngan-son-bac-kan-d33.html"),
            ("Nghi Lộc", "viec-lam-huyen-nghi-loc-nghe-an-d466.html"),
            ("Nghi Xuân", "viec-lam-huyen-nghi-xuan-ha-tinh-d267.html"),
            ("Nghĩa Đàn", "viec-lam-huyen-nghia-dan-nghe-an-d456.html"),
            ("Nghĩa Hành", "viec-lam-huyen-nghia-hanh-quang-ngai-d540.html"),
            ("Nghĩa Hưng", "viec-lam-huyen-nghia-hung-nam-dinh-d443.html"),
            ("Nghĩa Lộ", "viec-lam-thi-xa-nghia-lo-yen-bai-d698.html"),
            ("Ngô Quyền", "viec-lam-quan-ngo-quyen-hai-phong-d287.html"),
            ("Ngọc Hiển", "viec-lam-huyen-ngoc-hien-ca-mau-d107.html"),
            ("Ngọc Hồi", "viec-lam-huyen-ngoc-hoi-kon-tum-d379.html"),
            ("Ngọc Lặc", "viec-lam-huyen-ngoc-lac-thanh-hoa-d626.html"),
            ("Ngũ Hành Sơn", "viec-lam-quan-ngu-hanh-son-da-nang-d134.html"),
            ("Nguyên Bình", "viec-lam-huyen-nguyen-binh-cao-bang-d128.html"),
            ("Nhà Bè", "viec-lam-huyen-nha-be-tp-hcm-d330.html"),
            ("Nha Trang", "viec-lam-thanh-pho-nha-trang-khanh-hoa-d353.html"),
            ("Nho Quan", "viec-lam-huyen-nho-quan-ninh-binh-d471.html"),
            ("Nhơn Trạch", "viec-lam-huyen-nhon-trach-dong-nai-d185.html"),
            ("Như Thanh", "viec-lam-huyen-nhu-thanh-thanh-hoa-d640.html"),
            ("Như Xuân", "viec-lam-huyen-nhu-xuan-thanh-hoa-d639.html"),
            ("Ninh Bình", "viec-lam-thanh-pho-ninh-binh-ninh-binh-d469.html"),
            ("Ninh Giang", "viec-lam-huyen-ninh-giang-hai-duong-d284.html"),
            ("Ninh Hải", "viec-lam-huyen-ninh-hai-ninh-thuan-d480.html"),
            ("Ninh Hòa", "viec-lam-huyen-ninh-hoa-khanh-hoa-d357.html"),
            ("Ninh Kiều", "viec-lam-quan-ninh-kieu-can-tho-d108.html"),
            ("Ninh Phước", "viec-lam-huyen-ninh-phuoc-ninh-thuan-d481.html"),
            ("Ninh Sơn", "viec-lam-huyen-ninh-son-ninh-thuan-d479.html"),
            ("Nông Cống", "viec-lam-huyen-nong-cong-thanh-hoa-d641.html"),
            ("Nông Sơn", "viec-lam-huyen-nong-son-quang-nam-d530.html"),
            ("Núi Thành", "viec-lam-huyen-nui-thanh-quang-nam-d528.html"),
            ("Ô Môn", "viec-lam-quan-o-mon-can-tho-d109.html"),
            ("Pác Nặm", "viec-lam-huyen-pac-nam-bac-kan-d31.html"),
            ("Phan Rang", "viec-lam-thanh-pho-phan-rang-ninh-thuan-d477.html"),
            ("Phan Thiết", "viec-lam-thanh-pho-phan-thiet-binh-thuan-d89.html"),
            ("Phổ Yên", "viec-lam-huyen-pho-yen-thai-nguyen-d616.html"),
            ("Phong Điền", "viec-lam-huyen-phong-dien-can-tho-d115.html"),
            ("Phong Điền", "viec-lam-huyen-phong-dien-thua-thien-hue-d646.html"),
            ("Phong Thổ", "viec-lam-huyen-phong-tho-lai-chau-d390.html"),
            ("Phú Bình", "viec-lam-huyen-phu-binh-thai-nguyen-d617.html"),
            ("Phù Cát", "viec-lam-huyen-phu-cat-binh-dinh-d68.html"),
            ("Phù Cừ", "viec-lam-huyen-phu-cu-hung-yen-d352.html"),
            ("Phú Giáo", "viec-lam-huyen-phu-giao-binh-duong-d75.html"),
            ("Phú Hòa", "viec-lam-huyen-phu-hoa-phu-yen-d504.html"),
            ("Phú Lộc", "viec-lam-huyen-phu-loc-thua-thien-hue-d652.html"),
            ("Phú Lương", "viec-lam-huyen-phu-luong-thai-nguyen-d612.html"),
            ("Phủ Lý", "viec-lam-thanh-pho-phu-ly-ha-nam-d226.html"),
            ("Phú Mỹ", "viec-lam-huyen-phu-my-ba-ria-vung-tau-d18.html"),
            ("Phù Mỹ", "viec-lam-huyen-phu-my-binh-dinh-d65.html"),
            ("Phú Nhuận", "viec-lam-quan-phu-nhuan-tp-hcm-d316.html"),
            ("Phú Ninh", "viec-lam-huyen-phu-ninh-quang-nam-d529.html"),
            ("Phù Ninh", "viec-lam-huyen-phu-ninh-phu-tho-d489.html"),
            ("Phú Quốc", "viec-lam-huyen-phu-quoc-kien-giang-d373.html"),
            ("Phú Quý", "viec-lam-huyen-phu-qui-binh-thuan-d98.html"),
            ("Phú Riềng", "viec-lam-huyen-phu-rieng-binh-phuoc-d100000001.html"),
            ("Phú Tân", "viec-lam-huyen-phu-tan-an-giang-d5.html"),
            ("Phú Tân", "viec-lam-huyen-phu-tan-ca-mau-d106.html"),
            ("Phú Thiện", "viec-lam-huyen-phu-thien-gia-lai-d213.html"),
            ("Phú Thọ", "viec-lam-thi-xa-phu-tho-phu-tho-d485.html"),
            ("Phú Vang", "viec-lam-huyen-phu-vang-thua-thien-hue-d648.html"),
            ("Phú Xuyên", "viec-lam-huyen-phu-xuyen-ha-noi-d259.html"),
            ("Phù Yên", "viec-lam-huyen-phu-yen-son-la-d586.html"),
            ("Phục Hòa", "viec-lam-huyen-phuc-hoa-cao-bang-d126.html"),
            ("Phúc Thọ", "viec-lam-huyen-phuc-tho-ha-noi-d251.html"),
            ("Phúc Yên", "viec-lam-thi-xa-phuc-yen-vinh-phuc-d688.html"),
            ("Phụng Hiệp", "viec-lam-huyen-phung-hiep-hau-giang-d305.html"),
            ("Phước Long", "viec-lam-huyen-phuoc-long-bac-lieu-d40.html"),
            ("Phước Long", "viec-lam-thi-xa-phuoc-long-binh-phuoc-d80.html"),
            ("Phước Sơn", "viec-lam-huyen-phuoc-son-quang-nam-d522.html"),
            ("Pleiku", "viec-lam-thanh-pho-pleiku-gia-lai-d198.html"),
            ("Quản Bạ", "viec-lam-huyen-quan-ba-ha-giang-d219.html"),
            ("Quan Hóa", "viec-lam-huyen-quan-hoa-thanh-hoa-d622.html"),
            ("Quan Sơn", "viec-lam-huyen-quan-son-thanh-hoa-d624.html"),
            ("Quang Bình", "viec-lam-huyen-quang-binh-ha-giang-d225.html"),
            ("Quảng Điền", "viec-lam-huyen-quang-dien-thua-thien-hue-d647.html"),
            ("Quảng Ngãi", "viec-lam-thanh-pho-quang-ngai-quang-ngai-d531.html"),
            ("Quảng Ninh", "viec-lam-huyen-quang-ninh-quang-binh-d511.html"),
            ("Quảng Trạch", "viec-lam-huyen-quang-trach-quang-binh-d509.html"),
            ("Quảng Trị", "viec-lam-thi-xa-quang-tri-quang-tri-d561.html"),
            ("Quảng Uyên", "viec-lam-huyen-quang-uyen-cao-bang-d125.html"),
            ("Quảng Xương", "viec-lam-huyen-quang-xuong-thanh-hoa-d643.html"),
            ("Quảng Yên", "viec-lam-thi-xa-quang-yen-quang-ninh-d559.html"),
            ("Quế Phong", "viec-lam-huyen-que-phong-nghe-an-d452.html"),
            ("Quế Sơn", "viec-lam-huyen-que-son-quang-nam-d520.html"),
            ("Quế Võ", "viec-lam-huyen-que-vo-bac-ninh-d48.html"),
            ("Quốc Oai", "viec-lam-huyen-quoc-oai-ha-noi-d254.html"),
            ("Quỳ Châu", "viec-lam-huyen-quy-chau-nghe-an-d453.html"),
            ("Quỳ Hợp", "viec-lam-huyen-quy-hop-nghe-an-d457.html"),
            ("Quy Nhơn", "viec-lam-thanh-pho-quy-nhon-binh-dinh-d61.html"),
            ("Quỳnh Lưu", "viec-lam-huyen-quynh-luu-nghe-an-d458.html"),
            ("Quỳnh Nhai", "viec-lam-huyen-quynh-nhai-son-la-d582.html"),
            ("Quỳnh Phụ", "viec-lam-huyen-quynh-phu-thai-binh-d602.html"),
            ("Rạch Giá", "viec-lam-thanh-pho-rach-gia-kien-giang-d362.html"),
            ("Sa Đéc", "viec-lam-thi-xa-sa-dec-dong-thap-d187.html"),
            ("Sa Pa", "viec-lam-huyen-sa-pa-lao-cai-d423.html"),
            ("Sa Thầy", "viec-lam-huyen-sa-thay-kon-tum-d384.html"),
            ("Sầm Sơn", "viec-lam-thi-xa-sam-son-thanh-hoa-d620.html"),
            ("Si Ma Cai", "viec-lam-huyen-si-ma-cai-lao-cai-d419.html"),
            ("Sìn Hồ", "viec-lam-huyen-sin-ho-lai-chau-d389.html"),
            ("Sóc Sơn", "viec-lam-huyen-soc-son-ha-noi-d243.html"),
            ("Sóc Trăng", "viec-lam-thanh-pho-soc-trang-soc-trang-d570.html"),
            ("Sơn Dương", "viec-lam-huyen-son-duong-tuyen-quang-d677.html"),
            ("Sơn Động", "viec-lam-huyen-son-dong-bac-giang-d26.html"),
            ("Sơn Hà", "viec-lam-huyen-son-ha-quang-ngai-d537.html"),
            ("Sơn Hòa", "viec-lam-huyen-son-hoa-phu-yen-d501.html"),
            ("Sơn La", "viec-lam-thanh-pho-son-la-son-la-d581.html"),
            ("Sơn Tây", "viec-lam-huyen-son-tay-quang-ngai-d538.html"),
            ("Sơn Tây", "viec-lam-thi-xa-son-tay-ha-noi-d242.html"),
            ("Sơn Tịnh", "viec-lam-huyen-son-tinh-quang-ngai-d535.html"),
            ("Sơn Trà", "viec-lam-quan-son-tra-da-nang-d133.html"),
            ("Sông Cầu", "viec-lam-thi-xa-song-cau-phu-yen-d498.html"),
            ("Sông Công", "viec-lam-thi-xa-song-cong-thai-nguyen-d610.html"),
            ("Sông Hinh", "viec-lam-huyen-song-hinh-phu-yen-d502.html"),
            ("Sông Lô", "viec-lam-huyen-song-lo-vinh-phuc-d695.html"),
            ("Sông Mã", "viec-lam-huyen-song-ma-son-la-d590.html"),
            ("Sốp Cộp", "viec-lam-huyen-sop-cop-son-la-d591.html"),
            ("Tam Bình", "viec-lam-huyen-tam-binh-vinh-long-d683.html"),
            ("Tam Dương", "viec-lam-huyen-tam-duong-vinh-phuc-d690.html"),
            ("Tam Đảo", "viec-lam-huyen-tam-dao-vinh-phuc-d691.html"),
            ("Tam Điệp", "viec-lam-thi-xa-tam-diep-ninh-binh-d470.html"),
            ("Tam Đường", "viec-lam-huyen-tam-duong-lai-chau-d387.html"),
            ("Tam Kỳ", "viec-lam-thanh-pho-tam-ky-quang-nam-d513.html"),
            ("Tam Nông", "viec-lam-huyen-tam-nong-dong-thap-d191.html"),
            ("Tam Nông", "viec-lam-huyen-tam-nong-phu-tho-d492.html"),
            ("Tân An", "viec-lam-thanh-pho-tan-an-long-an-d425.html"),
            ("Tân Biên", "viec-lam-huyen-tan-bien-tay-ninh-d593.html"),
            ("Tân Bình", "viec-lam-quan-tan-binh-tp-hcm-d314.html"),
            ("Tân Châu", "viec-lam-huyen-tan-chau-an-giang-d4.html"),
            ("Tân Châu", "viec-lam-huyen-tan-chau-tay-ninh-d594.html"),
            ("Tân Hiệp", "viec-lam-huyen-tan-hiep-kien-giang-d366.html"),
            ("Tân Hồng", "viec-lam-huyen-tan-hong-dong-thap-d189.html"),
            ("Tân Hưng", "viec-lam-huyen-tan-hung-long-an-d426.html"),
            ("Tân Kỳ", "viec-lam-huyen-tan-ky-nghe-an-d460.html"),
            ("Tân Lạc", "viec-lam-huyen-tan-lac-hoa-binh-d338.html"),
            ("Tân Phú", "viec-lam-quan-tan-phu-tp-hcm-d315.html"),
            ("Tân Phú", "viec-lam-huyen-tan-phu-dong-nai-d177.html"),
            ("Tân Phú Đông", "viec-lam-huyen-tan-phu-dong-tien-giang-d663.html"),
            ("Tân Phước", "viec-lam-huyen-tan-phuoc-tien-giang-d656.html"),
            ("Tân Sơn", "viec-lam-huyen-tan-son-phu-tho-d496.html"),
            ("Tân Thạnh", "viec-lam-huyen-tan-thanh-long-an-d429.html"),
            ("Tân Trụ", "viec-lam-huyen-tan-tru-long-an-d435.html"),
            ("Tân Uyên", "viec-lam-huyen-tan-uyen-binh-duong-d76.html"),
            ("Tân Uyên", "viec-lam-huyen-tan-uyen-lai-chau-d392.html"),
            ("Tân Yên", "viec-lam-huyen-tan-yen-bac-giang-d22.html"),
            ("Tánh Linh", "viec-lam-huyen-tanh-linh-binh-thuan-d95.html"),
            ("Tây Giang", "viec-lam-huyen-tay-giang-quang-nam-d515.html"),
            ("Tây Hồ", "viec-lam-quan-tay-ho-ha-noi-d234.html"),
            ("Tây Hòa", "viec-lam-huyen-tay-hoa-phu-yen-d503.html"),
            ("Tây Ninh", "viec-lam-thi-xa-tay-ninh-tay-ninh-d592.html"),
            ("Tây Sơn", "viec-lam-huyen-tay-son-binh-dinh-d67.html"),
            ("Tây Trà", "viec-lam-huyen-tay-tra-quang-ngai-d534.html"),
            ("Thạch An", "viec-lam-huyen-thach-an-cao-bang-d129.html"),
            ("Thạch Hà", "viec-lam-huyen-thach-ha-ha-tinh-d270.html"),
            ("Thạch Thành", "viec-lam-huyen-thach-thanh-thanh-hoa-d628.html"),
            ("Thạch Thất", "viec-lam-huyen-thach-that-ha-noi-d255.html"),
            ("Thái Bình", "viec-lam-thanh-pho-thai-binh-thai-binh-d601.html"),
            ("Thái Hòa", "viec-lam-thi-xa-thai-hoa-nghe-an-d451.html"),
            ("Thái Nguyên", "viec-lam-thanh-pho-thai-nguyen-thai-nguyen-d609.html"),
            ("Thái Thụy", "viec-lam-huyen-thai-thuy-thai-binh-d605.html"),
            ("Than Uyên", "viec-lam-huyen-than-uyen-lai-chau-d391.html"),
            ("Thăng Bình", "viec-lam-huyen-thang-binh-quang-nam-d524.html"),
            ("Thanh Ba", "viec-lam-huyen-thanh-ba-phu-tho-d488.html"),
            ("Thanh Bình", "viec-lam-huyen-thanh-binh-dong-thap-d194.html"),
            ("Thanh Chương", "viec-lam-huyen-thanh-chuong-nghe-an-d465.html"),
            ("Thanh Hà", "viec-lam-huyen-thanh-ha-hai-duong-d279.html"),
            ("Thanh Hóa", "viec-lam-thanh-pho-thanh-hoa-thanh-hoa-d618.html"),
            ("Thạnh Hóa", "viec-lam-huyen-thanh-hoa-long-an-d430.html"),
            ("Thanh Khê", "viec-lam-quan-thanh-khe-da-nang-d131.html"),
            ("Thanh Liêm", "viec-lam-huyen-thanh-liem-ha-nam-d229.html"),
            ("Thanh Miện", "viec-lam-huyen-thanh-mien-hai-duong-d285.html"),
            ("Thanh Oai", "viec-lam-huyen-thanh-oai-ha-noi-d257.html"),
            ("Thạnh Phú", "viec-lam-huyen-thanh-phu-ben-tre-d60.html"),
            ("Thanh Sơn", "viec-lam-huyen-thanh-son-phu-tho-d494.html"),
            ("Thanh Thủy", "viec-lam-huyen-thanh-thuy-phu-tho-d495.html"),
            ("Thạnh Trị", "viec-lam-huyen-thanh-tri-soc-trang-d578.html"),
            ("Thanh Trì", "viec-lam-huyen-thanh-tri-ha-noi-d248.html"),
            ("Thanh Xuân", "viec-lam-quan-thanh-xuan-ha-noi-d240.html"),
            ("Tháp Mười", "viec-lam-huyen-thap-muoi-dong-thap-d192.html"),
            ("Thiệu Hóa", "viec-lam-huyen-thieu-hoa-thanh-hoa-d635.html"),
            ("Thọ Xuân", "viec-lam-huyen-tho-xuan-thanh-hoa-d632.html"),
            ("Thoại Sơn", "viec-lam-huyen-thoai-son-an-giang-d11.html"),
            ("Thới Bình", "viec-lam-huyen-thoi-binh-ca-mau-d101.html"),
            ("Thới Lai", "viec-lam-huyen-thoi-lai-can-tho-d116.html"),
            ("Thống Nhất", "viec-lam-huyen-thong-nhat-dong-nai-d181.html"),
            ("Thông Nông", "viec-lam-huyen-thong-nong-cao-bang-d120.html"),
            ("Thốt Nốt", "viec-lam-quan-thot-not-can-tho-d112.html"),
            ("Thủ Dầu Một", "viec-lam-thanh-pho-thu-dau-mot-binh-duong-d72.html"),
            ("Thủ Đức", "viec-lam-quan-thu-duc-tp-hcm-d310.html"),
            ("Thủ Thừa", "viec-lam-huyen-thu-thua-long-an-d434.html"),
            ("Thuận An", "viec-lam-thi-xa-thuan-an-binh-duong-d78.html"),
            ("Thuận Bắc", "viec-lam-huyen-thuan-bac-ninh-thuan-d482.html"),
            ("Thuận Châu", "viec-lam-huyen-thuan-chau-son-la-d583.html"),
            ("Thuận Nam", "viec-lam-huyen-thuan-nam-ninh-thuan-d483.html"),
            ("Thuận Thành", "viec-lam-huyen-thuan-thanh-bac-ninh-d50.html"),
            ("Thường Tín", "viec-lam-huyen-thuong-tin-ha-noi-d258.html"),
            ("Thường Xuân", "viec-lam-huyen-thuong-xuan-thanh-hoa-d633.html"),
            ("Thủy Nguyên", "viec-lam-huyen-thuy-nguyen-hai-phong-d293.html"),
            ("Tiên Du", "viec-lam-huyen-tien-du-bac-ninh-d49.html"),
            ("Tiền Hải", "viec-lam-huyen-tien-hai-thai-binh-d606.html"),
            ("Tiên Lãng", "viec-lam-huyen-tien-lang-hai-phong-d297.html"),
            ("Tiên Lữ", "viec-lam-huyen-tien-lu-hung-yen-d351.html"),
            ("Tiên Phước", "viec-lam-huyen-tien-phuoc-quang-nam-d525.html"),
            ("Tiên Yên", "viec-lam-huyen-tien-yen-quang-ninh-d550.html"),
            ("Tiểu Cần", "viec-lam-huyen-tieu-can-tra-vinh-d667.html"),
            ("Tịnh Biên", "viec-lam-huyen-tinh-bien-an-giang-d7.html"),
            ("Tĩnh Gia", "viec-lam-huyen-tinh-gia-thanh-hoa-d644.html"),
            ("Trà Bồng", "viec-lam-huyen-tra-bong-quang-ngai-d533.html"),
            ("Trà Cú", "viec-lam-huyen-tra-cu-tra-vinh-d670.html"),
            ("Trà Lĩnh", "viec-lam-huyen-tra-linh-cao-bang-d122.html"),
            ("Trà Ôn", "viec-lam-huyen-tra-on-vinh-long-d685.html"),
            ("Trà Vinh", "viec-lam-thanh-pho-tra-vinh-tra-vinh-d664.html"),
            ("Trạm Tấu", "viec-lam-huyen-tram-tau-yen-bai-d703.html"),
            ("Trần Đề", "viec-lam-huyen-tran-de-soc-trang-d580.html"),
            ("Trần Văn Thời", "viec-lam-huyen-tran-van-thoi-ca-mau-d102.html"),
            ("Trấn Yên", "viec-lam-huyen-tran-yen-yen-bai-d702.html"),
            ("Trảng Bàng", "viec-lam-huyen-trang-bang-tay-ninh-d600.html"),
            ("Trảng Bom", "viec-lam-huyen-trang-bom-dong-nai-d180.html"),
            ("Tràng Định", "viec-lam-huyen-trang-dinh-lang-son-d406.html"),
            ("Tri Tôn", "viec-lam-huyen-tri-ton-an-giang-d8.html"),
            ("Triệu Phong", "viec-lam-huyen-trieu-phong-quang-tri-d567.html"),
            ("Triệu Sơn", "viec-lam-huyen-trieu-son-thanh-hoa-d634.html"),
            ("Trực Ninh", "viec-lam-huyen-truc-ninh-nam-dinh-d445.html"),
            ("Trùng Khánh", "viec-lam-huyen-trung-khanh-cao-bang-d123.html"),
            ("Trường Sa", "viec-lam-huyen-truong-sa-khanh-hoa-d361.html"),
            ("Tứ Kỳ", "viec-lam-huyen-tu-ky-hai-duong-d283.html"),
            ("Tu Mơ Rông", "viec-lam-huyen-tu-mo-rong-kon-tum-d385.html"),
            ("Tư Nghĩa", "viec-lam-huyen-tu-nghia-quang-ngai-d536.html"),
            ("Từ Sơn", "viec-lam-thi-xa-tu-son-bac-ninh-d46.html"),
            ("Tủa Chùa", "viec-lam-huyen-tua-chua-dien-bien-d169.html"),
            ("Tuần Giáo", "viec-lam-huyen-tuan-giao-dien-bien-d170.html"),
            ("Tương Dương", "viec-lam-huyen-tuong-duong-nghe-an-d455.html"),
            ("Tuy An", "viec-lam-huyen-tuy-an-phu-yen-d500.html"),
            ("Tuy Đức", "viec-lam-huyen-tuy-duc-dak-nong-d164.html"),
            ("Tuy Hòa", "viec-lam-thanh-pho-tuy-hoa-phu-yen-d497.html"),
            ("Tuy Phong", "viec-lam-huyen-tuy-phong-binh-thuan-d91.html"),
            ("Tuy Phước", "viec-lam-huyen-tuy-phuoc-binh-dinh-d70.html"),
            ("Tuyên Hóa", "viec-lam-huyen-tuyen-hoa-quang-binh-d508.html"),
            ("Tuyên Quang", "viec-lam-thi-xa-tuyen-quang-tuyen-quang-d672.html"),
            ("U Minh", "viec-lam-huyen-u-minh-ca-mau-d100.html"),
            ("U Minh Thượng", "viec-lam-huyen-u-minh-thuong-kien-giang-d375.html"),
            ("Ứng Hòa", "viec-lam-huyen-ung-hoa-ha-noi-d260.html"),
            ("Uông Bí", "viec-lam-thanh-pho-uong-bi-quang-ninh-d548.html"),
            ("Văn Bàn", "viec-lam-huyen-van-ban-lao-cai-d424.html"),
            ("Vân Canh", "viec-lam-huyen-van-canh-binh-dinh-d71.html"),
            ("Văn Chấn", "viec-lam-huyen-van-chan-yen-bai-d704.html"),
            ("Vân Đồn", "viec-lam-huyen-van-don-quang-ninh-d554.html"),
            ("Văn Giang", "viec-lam-huyen-van-giang-hung-yen-d345.html"),
            ("Văn Lâm", "viec-lam-huyen-van-lam-hung-yen-d344.html"),
            ("Văn Lãng", "viec-lam-huyen-van-lang-lang-son-d408.html"),
            ("Vạn Ninh", "viec-lam-huyen-van-ninh-khanh-hoa-d356.html"),
            ("Văn Quan", "viec-lam-huyen-van-quan-lang-son-d410.html"),
            ("Văn Yên", "viec-lam-huyen-van-yen-yen-bai-d700.html"),
            ("Vị Thanh", "viec-lam-thanh-pho-vi-thanh-hau-giang-d301.html"),
            ("Vị Thủy", "viec-lam-huyen-vi-thuy-hau-giang-d306.html"),
            ("Vị Xuyên", "viec-lam-huyen-vi-xuyen-ha-giang-d220.html"),
            ("Việt Trì", "viec-lam-thanh-pho-viet-tri-phu-tho-d484.html"),
            ("Việt Yên", "viec-lam-huyen-viet-yen-bac-giang-d28.html"),
            ("Vinh", "viec-lam-thanh-pho-vinh-nghe-an-d449.html"),
            ("Vĩnh Bảo", "viec-lam-huyen-vinh-bao-hai-phong-d298.html"),
            ("Vĩnh Châu", "viec-lam-thi-xa-vinh-chau-soc-trang-d579.html"),
            ("Vĩnh Cửu", "viec-lam-huyen-vinh-cuu-dong-nai-d178.html"),
            ("Vĩnh Hưng", "viec-lam-huyen-vinh-hung-long-an-d427.html"),
            ("Vĩnh Linh", "viec-lam-huyen-vinh-linh-quang-tri-d562.html"),
            ("Vĩnh Lộc", "viec-lam-huyen-vinh-loc-thanh-hoa-d630.html"),
            ("Vĩnh Lợi", "viec-lam-huyen-vinh-loi-bac-lieu-d41.html"),
            ("Vĩnh Long", "viec-lam-thanh-pho-vinh-long-vinh-long-d679.html"),
            ("Vĩnh Thạnh", "viec-lam-huyen-vinh-thanh-binh-dinh-d66.html"),
            ("Vĩnh Thạnh", "viec-lam-huyen-vinh-thanh-can-tho-d113.html"),
            ("Vĩnh Thuận", "viec-lam-huyen-vinh-thuan-kien-giang-d372.html"),
            ("Vĩnh Tường", "viec-lam-huyen-vinh-tuong-vinh-phuc-d694.html"),
            ("Vĩnh Yên", "viec-lam-thanh-pho-vinh-yen-vinh-phuc-d687.html"),
            ("Võ Nhai", "viec-lam-huyen-vo-nhai-thai-nguyen-d614.html"),
            ("Vụ Bản", "viec-lam-huyen-vu-ban-nam-dinh-d441.html"),
            ("Vũ Quang", "viec-lam-huyen-vu-quang-ha-tinh-d266.html"),
            ("Vũ Thư", "viec-lam-huyen-vu-thu-thai-binh-d608.html"),
            ("Vũng Liêm", "viec-lam-huyen-vung-liem-vinh-long-d682.html"),
            ("Vũng Tàu", "viec-lam-thanh-pho-vung-tau-ba-ria-vung-tau-d12.html"),
            ("Xín Mần", "viec-lam-huyen-xin-man-ha-giang-d223.html"),
            ("Xuân Lộc", "viec-lam-huyen-xuan-loc-dong-nai-d184.html"),
            ("Xuân Trường", "viec-lam-huyen-xuan-truong-nam-dinh-d446.html"),
            ("Xuyên Mộc", "viec-lam-huyen-xuyen-moc-ba-ria-vung-tau-d15.html"),
            ("Ý Yên", "viec-lam-huyen-y-yen-nam-dinh-d442.html"),
            ("Yên Bái", "viec-lam-thanh-pho-yen-bai-yen-bai-d697.html"),
            ("Yên Bình", "viec-lam-huyen-yen-binh-yen-bai-d705.html"),
            ("Yên Châu", "viec-lam-huyen-yen-chau-son-la-d588.html"),
            ("Yên Dũng", "viec-lam-huyen-yen-dung-bac-giang-d27.html"),
            ("Yên Định", "viec-lam-huyen-yen-dinh-thanh-hoa-d631.html"),
            ("Yên Hưng", "viec-lam-huyen-yen-hung-quang-ninh-d557.html"),
            ("Yên Khánh", "viec-lam-huyen-yen-khanh-ninh-binh-d474.html"),
            ("Yên Lạc", "viec-lam-huyen-yen-lac-vinh-phuc-d693.html"),
            ("Yên Lập", "viec-lam-huyen-yen-lap-phu-tho-d490.html"),
            ("Yên Minh", "viec-lam-huyen-yen-minh-ha-giang-d218.html"),
            ("Yên Mô", "viec-lam-huyen-yen-mo-ninh-binh-d476.html"),
            ("Yên Mỹ", "viec-lam-huyen-yen-my-hung-yen-d346.html"),
            ("Yên Phong", "viec-lam-huyen-yen-phong-bac-ninh-d47.html"),
            ("Yên Sơn", "viec-lam-huyen-yen-son-tuyen-quang-d676.html"),
            ("Yên Thành", "viec-lam-huyen-yen-thanh-nghe-an-d463.html"),
            ("Yên Thế", "viec-lam-huyen-yen-the-bac-giang-d21.html"),
            ("Yên Thủy", "viec-lam-huyen-yen-thuy-hoa-binh-d341.html"),
        }.ToLookup(entry => entry.Name, entry => entry.Path, System.StringComparer.OrdinalIgnoreCase);
    }
}
