// <auto-generated />
using System;
using JobAggregator.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobAggregator.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904174726_AddJobInfoFields")]
    partial class AddJobInfoFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobAggregator.DataAccess.Entities.JobPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgeRequirement")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmployerName")
                        .HasColumnType("text");

                    b.Property<string>("Experience")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("HolidayBonuses")
                        .HasColumnType("text");

                    b.Property<string>("JobInfo")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("OtherBenefits")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("SalaryInfo")
                        .HasColumnType("text");

                    b.Property<Guid>("SearchKeywordId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecificAddress")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Vacancies")
                        .HasColumnType("integer");

                    b.Property<string>("WorkingDays")
                        .HasColumnType("text");

                    b.Property<string>("WorkingFormat")
                        .HasColumnType("text");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SearchKeywordId");

                    b.HasIndex("Platform", "ExternalId")
                        .IsUnique();

                    b.ToTable("JobPosts");
                });

            modelBuilder.Entity("JobAggregator.DataAccess.Entities.SearchKeyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalJobsFound")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SearchKeywords");
                });

            modelBuilder.Entity("JobAggregator.DataAccess.Entities.WebSocketConnection", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConnectionId");

                    b.ToTable("WebSocketConnections");
                });

            modelBuilder.Entity("JobAggregator.DataAccess.Entities.JobPost", b =>
                {
                    b.HasOne("JobAggregator.DataAccess.Entities.SearchKeyword", "SearchKeyword")
                        .WithMany("JobPosts")
                        .HasForeignKey("SearchKeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchKeyword");
                });

            modelBuilder.Entity("JobAggregator.DataAccess.Entities.SearchKeyword", b =>
                {
                    b.Navigation("JobPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
