// <auto-generated />
using System;
using JobAggregator.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobAggregator.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916153032_AddFacebookCatalogAndScrapeRuns")]
    partial class AddFacebookCatalogAndScrapeRuns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobAggregator.DataAccess.Entities.FacebookGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalGroupId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSuccessfulScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalUrl")
                        .IsUnique();

                    b.HasIndex("ExternalGroupId")
                        .IsUnique();

                    b.ToTable("FacebookGroups");
                });

            modelBuilder.Entity("JobAggregator.DataAccess.Entities.JobLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExactAddress")
                        .HasColumnType("text");

                    b.Property<Guid>("JobPostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.HasIndex("Province", "District");

                    b.ToTable("JobLocations");
                });

            modelBuilder.Entity("JobAggregator.DataAccess.Entities.JobPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgeRequirement")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmployerName")
                        .HasColumnType("text");

                    b.Property<string>("Experience")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FacebookGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("HolidayBonuses")
                        .HasColumnType("text");

                    b.Property<string>("JobInfo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("OtherBenefits")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string[]>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("SalaryInfo")
                        .HasColumnType("text");

                    b.Property<Guid>("SearchKeywordId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Vacancies")
                        .HasColumnType("integer");

                    b.Property<string>("WorkingDays")
                        .HasColumnType("text");

                    b.Property<string>("WorkingFormat")
                        .HasColumnType("text");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SearchKeywordId");

                    b.HasIndex("Platform", "ExternalId")
                        .IsUnique();

                    b.HasIndex("FacebookGroupId", "PostedDate", "Id");

                    b.HasIndex("Platform", "PostedDate", "Id");

                    b.ToTable("JobPosts");
                });

            modelBuilder.Entity("JobAggregator.DataAccess.Entities.JobSearchRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApifyRunId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FacebookGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("FetchedCount")
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text");

                    b.Property<int>("InsertedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessingResultsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawDataKey")
                        .HasColumnType("text");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("integer");

                    b.Property<int>("RequestedLimit")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnchangedCount")
                        .HasColumnType("integer");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FacebookGroupId");

                    b.HasIndex("OwnerId", "CreatedAt");

                    b.HasIndex("OwnerId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ScopeKey", "CreatedAt");

                    b.ToTable("JobSearchRequests");
                });

            modelBuilder.Entity("JobAggregator.DataAccess.Entities.SearchKeyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalJobsFound")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SearchKeywords");
                });

            modelBuilder.Entity("JobAggregator.DataAccess.Entities.WebSocketConnection", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConnectionId");

                    b.ToTable("WebSocketConnections");
                });

            modelBuilder.Entity("JobAggregator.DataAccess.Entities.JobLocation", b =>
                {
                    b.HasOne("JobAggregator.DataAccess.Entities.JobPost", "JobPost")
                        .WithMany("Locations")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("JobAggregator.DataAccess.Entities.JobPost", b =>
                {
                    b.HasOne("JobAggregator.DataAccess.Entities.FacebookGroup", "FacebookGroup")
                        .WithMany()
                        .HasForeignKey("FacebookGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JobAggregator.DataAccess.Entities.SearchKeyword", "SearchKeyword")
                        .WithMany("JobPosts")
                        .HasForeignKey("SearchKeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacebookGroup");

                    b.Navigation("SearchKeyword");
                });

            modelBuilder.Entity("JobAggregator.DataAccess.Entities.JobSearchRequest", b =>
                {
                    b.HasOne("JobAggregator.DataAccess.Entities.FacebookGroup", "FacebookGroup")
                        .WithMany()
                        .HasForeignKey("FacebookGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FacebookGroup");
                });

            modelBuilder.Entity("JobAggregator.DataAccess.Entities.JobPost", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("JobAggregator.DataAccess.Entities.SearchKeyword", b =>
                {
                    b.Navigation("JobPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
